apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-buxc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-buxc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-buxc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-buxc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-buxc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-hjjf-tenant/rhtap-demo-app/hacbs-test-project-buxc@sha256:93586abe46c87c5932dc11070de5f6d2299d8a9fffea979a4bf0101c82fbd085
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
